"""empty message

Revision ID: 26977f2132f6
Revises: 56d3196af612
Create Date: 2020-05-21 20:47:03.170612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26977f2132f6'
down_revision = '56d3196af612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=140), nullable=True),
    sa.Column('pot', sa.String(length=140), nullable=True),
    sa.Column('watering_frequency', sa.Integer(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_last_watered'), 'plant', ['last_watered'], unique=False)
    op.drop_index('ix_plants_last_watered', table_name='plants')
    op.drop_table('plants')
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=140), nullable=True),
    sa.Column('pot', sa.VARCHAR(length=140), nullable=True),
    sa.Column('watering_frequency', sa.INTEGER(), nullable=True),
    sa.Column('last_watered', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plants_last_watered', 'plants', ['last_watered'], unique=False)
    op.drop_index(op.f('ix_plant_last_watered'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
